theme: jekyll-theme-minimal
title: Gautham Umasankar
description: All equations speak, we just have to listen
future: true
timezone: NP
github:
  is_project_page: false
logo: https://lh3.googleusercontent.com/pw/AM-JKLWIw3qGRm-EOVtbcyJooJpFec0QcxPznMbtPdYC4Cn9Y9fLQ8gjwAf-w9oXr75rWVHnxzp9rA58-jY9e_Wjku0FP41PkV8zX6Hlia1Q0umCKL9APwcL8G70vg2ecYpf4GNhev1lYmuNyeeibOHxoxN7XA=w850-h637-no?authuser=0
