theme: jekyll-theme-minimal
title: Gautham Umasankar
description: All equations speak, we just have to listen
future: true
timezone: NP
github:
  is_project_page: false
logo: https://photos.app.goo.gl/iZFdcPzCAdqy7ywH7
