theme: jekyll-theme-dinky
title: "<a href='https://gautham-umasankar.github.io'> Gautham Umasankar</a>"
description: "All equations speak, we just have to listen <br> <a class=\"buttons github\" href=\"https://github.com/gautham-umasankar/gautham-umasankar.github.io\">GitHub Profile</a>"
future: true
timezone: NP
github:
  is_project_page: false
logo: https://lh3.googleusercontent.com/pw/AM-JKLVyLRcS63oCJZOxFIoGQDl1LmMJ3vlFIuFAtJOLcSeAJtha2aFdFcfYRVnEoLzNPI9b5eFZDFQvePGJMXj6ZeY64oys-ehabOlreViy9jc5rfxx2h_751qYtYyuVk22G9-3-VlGPbaRhHXiitjy0wgr5g=w610-h637-no?authuser=0
